version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes: 
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  easy-notes:
    build: . #local Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes: 
  mongodb-data: